Test for zero allocation flow (#195)
* test for 1 allocs to check the error message

* remove file from annotation

* return nonzero error code along with error message

* fix yaml syntax error

* switch to zero allocations for real

* adjust wording in error message

* also output go test output to stderr

* break test again

* fix the test again

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,3 +25,11 @@ jobs:
 
     - name: Test that CGO is not required for native bucketing
       run: CGO_ENABLED=0 go test -run="^$" ./...
+      
+    - name: Test that variable evaluation requires zero heap allocations
+      run: >
+        go test -run=^$ -bench "^Benchmark.*_VariableSerial$" -benchmem .
+        | tee /dev/stderr
+        | grep '0 allocs/op'
+        || ( echo "::error title=Heap allocations detected in variable evaluations::The variable evaluation flow cannot have any allocations, or performance will degrade at high concurrency. See https://www.notion.so/How-to-profile-with-Go-613eb85b95c74df898552958f6b1541f for more information on how to resolve this."; false )
+
